[build]
  base = "pips-web/"
  publish = "dist/pips-web/"
  command = "npm run build:prod"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  headers = { X-Clacks-Overhead = "GNU Terry Pratchett" }
