name: Cargo Publish

on:
  push:
    tags:
      - "pips-v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --all --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Cargo publish
        run: |
          cargo publish \
            --token ${{ secrets.CARGO_REGISTRY_TOKEN }} \
            --no-verify \
            --manifest-path ./Cargo.toml
