name: NPM Publish

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # install the latest version of wasm-pack
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - name: Build wasm package
        run: ./build-wasm.sh

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: pips-wasm/pkg/package.json
